feat: vendor cyrus-sasl & openldap
NO_DOC=picodata internal patch
NO_CHANGELOG=picodata internal patch
NO_TEST=picodata internal patch

fix(build): Prevent sasl's makefile rules from staining vendor

Turns out Cyrus SASL doesn't use AM_MAINTAINER_MODE or anything to
prevent autotools from re-configuring the project at build time.
This patch "fixes" that by maiming autotools' paths in Makefile.

NO_DOC=internal
NO_TEST=internal
NO_CHANGELOG=internal

fix(build): add missing headers to libsasl

NO_DOC=internal
NO_TEST=internal
NO_CHANGELOG=internal

This patch fixes the following problem at build time:

```
cyrus-sasl-2.1.28/lib/saslutil.c:280:3: error: implicit declaration of function 'time' [-Wimplicit-function-declaration]
280 |   time(&now);
    |   ^~~~
cyrus-sasl-2.1.28/lib/saslutil.c:66:1: note: 'time' is defined in header '<time.h>'; this is probably fixable by adding '#include <time.h>'
 65 | #include "saslint.h"
+++ |+#include <time.h>
 66 | #include <saslutil.h>
cyrus-sasl-2.1.28/lib/saslutil.c: In function 'getranddata':
cyrus-sasl-2.1.28/lib/saslutil.c:364:41: error: implicit declaration of function 'clock' [-Wimplicit-function-declaration]
364 |             ret[1] ^= (unsigned short) (clock() & 0xFFFF);
    |                                         ^~~~~
cyrus-sasl-2.1.28/lib/saslutil.c:364:41: note: 'clock' is defined in header '<time.h>'; this is probably fixable by adding '#include <time.h>'
cyrus-sasl-2.1.28/lib/saslutil.c: In function 'get_fqhostname':
cyrus-sasl-2.1.28/lib/saslutil.c:563:42: warning: comparison of integer expressions of different signedness: 'size_t' {aka 'long unsigned int'} and 'int' [-Wsign-compare]
563 |         || strlen (result->ai_canonname) > namelen -1) {
    |                                          ^
make[9]: *** [Makefile:643: saslutil.lo] Error 1
```